{
 "title": "Log Lupus Helper",
 "description": "Tracks VRChat tickets",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Total Tickets (24h)",
   "type": "stat",
   "description": "Total amount of tickets with a graph that shows last 24h",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(type) (\r\n   resolved_tickets{}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tracked Objects (24h)",
   "type": "stat",
   "description": "All tracked tickets with a graph that shows the last 24h",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum (tickets_info{})", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Unresolved Tickets (24h)",
   "type": "stat",
   "description": "A number and graph of the amount of unresolved tickets of the past 24h",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (tickets_info{emailCount=~\"[1]\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tickets Resolved",
   "type": "barchart",
   "description": "The delta of resolved tickets from the past hours",
   "gridPos": { "h": 10, "w": 11, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(type) (\r\n  label_replace(\r\n    delta(resolved_tickets[1h]), \r\n    \"type\", \"$1\", \"name\", \"^(avatar|user|group|world)-.*\"\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taken down Tickets",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(type) (\r\n  label_replace(\r\n    delta(resolved_tickets[$__range]), \r\n    \"type\", \"$1\", \"name\", \"^(avatar|user|group|world)-.*\"\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tickets resolved per day (2w)",
   "type": "stat",
   "description": "How many tickets are resolved per day on average based on 2 weeks of data",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  increase(resolved_tickets[1d])\r\n) \r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "All tickets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Ticket count",
   "type": "piechart",
   "description": "A total ticket count, split up by the different categories.",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(type) (\r\n  label_replace(resolved_tickets, \"type\", \"$1\", \"name\", \"^(avatar|user|group|world)-.*\")\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Report Types",
   "type": "piechart",
   "description": "A total amount of all categories sorted by reporting type.",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(reason) (\r\n  label_replace(\r\n    resolved_tickets{name=~\".*-(badgroupname|badworldname|badusername)\"},\r\n    \"reason\", \"badname\", \"name\", \".*\"\r\n  )\r\n  or\r\n  label_replace(\r\n    resolved_tickets{name!~\".*-(badgroupname|badworldname|badusername)\"},\r\n    \"reason\", \"$2\", \"name\", \"^(avatar|user|group|world)-(.*)\"\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ticket history",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 11 },
   "targets": [
    { "expr": "sum(resolved_tickets{}) ", "legendFormat": "All" },
    {
     "expr": "sum by(type) (\r\n  label_replace(\r\n    resolved_tickets{name=~\"avatar-.*\"},\r\n    \"type\", \"$1\", \"name\", \"^(avatar)-.*\"\r\n  )\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(type) (\r\n  label_replace(\r\n    resolved_tickets{name=~\"user-.*\"},\r\n    \"type\", \"$1\", \"name\", \"^(user)-.*\"\r\n  )\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(type) (\r\n  label_replace(\r\n    resolved_tickets{name=~\"group-.*\"},\r\n    \"type\", \"$1\", \"name\", \"^(group)-.*\"\r\n  )\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(type) (\r\n  label_replace(\r\n    resolved_tickets{name=~\"world-.*\"},\r\n    \"type\", \"$1\", \"name\", \"^(world)-.*\"\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Currently Open", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Tracked Tickets",
   "type": "timeseries",
   "description": "Stats of tracked tickets",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum (tickets_info{})", "legendFormat": "Tickets Tracked" },
    {
     "expr": "sum (tickets_info{emailCount=~\"[2-9]\"})",
     "legendFormat": "Tickets Resolved"
    },
    {
     "expr": "sum (tickets_info{emailCount=~\"[1]\"})",
     "legendFormat": "Tickets Unresolved"
    },
    {
     "expr": "sum (tickets_info{emailCount=~\"[0]\"})",
     "legendFormat": "Tickets None"
    },
    {
     "expr": "label_replace(\r\n  sum by(name) (tickets_info{emailCount=~\"[2-9]\"}), \r\n  \"group\", \"$1\", \"name\", \"(.*)\"\r\n)",
     "legendFormat": "Resolved {{name}}"
    },
    {
     "expr": "label_replace(\r\n  sum by(name) (tickets_info{emailCount=~\"[1]\"}), \r\n  \"group\", \"$1\", \"name\", \"(.*)\"\r\n)",
     "legendFormat": "Unresolved {{name}}"
    },
    {
     "expr": "label_replace(\r\n  sum by(name) (tickets_info{emailCount=~\"[0]\"}), \r\n  \"group\", \"$1\", \"name\", \"(.*)\"\r\n)",
     "legendFormat": "No Ticket {{name}}"
    }
   ]
  }
 ]
}